apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "govanity.fullname" . }}
  labels:
    {{- include "govanity.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.configuration | indent 4 }}