# main project identifier
project_name: govanity
# produced artifacts are stored in this folder
dist: dist
# customize execution
before:
  hooks:
    - go mod download
    - go generate ./...
    - docker login ghcr.io -u {{ .Env.GITHUB_USER }} -p {{ .Env.GITHUB_TOKEN }}
# artifacts to produce
# https://goreleaser.com/customization/build/
builds:
  # a single project can support/require several build targets
  - id: govanity
    # main binary name
    binary: govanity
    # CLI flags for the 'go build' command
    flags:
      -v
    ldflags:
      - -s -w
      - -X main.coreVersion={{.Version}}
      - -X main.buildCode={{.Commit}}
      - -X main.buildTimestamp={{.CommitDate}}
    # set the modified timestamp on the output binary to ensure a
    # reproducible build
    mod_timestamp: '{{ .CommitTimestamp }}'
    # disable CGO since it's not supported
    env:
      - CGO_ENABLED=0
    # supported OSs
    goos:
      - linux
      - windows
      - darwin
    # supported architectures
    goarch:
      - amd64
      - arm64
    # windows ARM is not supported
    ignore:
      - goos: windows
        goarch: arm64
# packages to produce
# https://goreleaser.com/customization/archive/
archives:
  # a single project can produce multiple archives
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
# generate integrity checksums
# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256
# Include source code package on the release
# https://goreleaser.com/customization/source/
source:
  enabled: true
# produce test releases
# https://goreleaser.com/customization/snapshots/
snapshot:
  name_template: "{{ .Version }}-next"
# configure the 'CHANGELOG.md' file produced
# https://goreleaser.com/customization/release/#customize-the-changelog
changelog:
  # Sorts the changelog by the commit messages (asc, desc or '')
  sort: ''
  # Remove certain commit messages from the changelog
  filters:
    # Standard commit messages can help to produce better changelogs
    # https://www.conventionalcommits.org/en/v1.0.0/
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^typo:"
# build and publish docker images
# https://goreleaser.com/customization/docker/
dockers:
  -
    # Build IDs to gather the binaries from
    ids:
      - govanity
    # GOOS of the built binary that should be used
    goos: linux
    # GOARCH of the built binary that should be used
    goarch: amd64
    # Dockerfile location
    dockerfile: Dockerfile
    # OCI image tags
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .CommitDate }}"
      - "--label=org.opencontainers.image.source=https://github.com/bryk-io/{{ .ProjectName }}"
    # Skips the docker push if there is an indicator for prerelease
    # in the tag e.g. v1.0.0-rc1 (auto)
    skip_push: "false"
    # Additional files to add/copy into the container image
    extra_files: []
    image_templates:
      - "ghcr.io/bryk-io/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/bryk-io/{{ .ProjectName }}:latest"
# Produce homebrew formulas for the project artifacts
# https://goreleaser.com/customization/homebrew/
brews:
  -
    # Formula name
    name: govanity
    # Push the formula to the tap repository
    skip_upload: "false"
    # TAP repository
    tap:
      owner: bryk-io
      name: homebrew-tap
    # Use 'github-actions' as commit author
    # https://github.community/t/github-actions-bot-email-address/17204
    commit_author:
      name: github-actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: 'https://github.com/bryk-io/go-vanity'
    description: |
      Basic 'Remote Import Path' server for Golang packages.
    install: |
      bin.install "govanity"
    test: |
      system "#{bin}/govanity -h"
